### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by ddkwork** [goradd/maps#15]
```go
	var (
		enumDebuggers = new(maps.SafeSliceMap[string, string])
		enumIoctls    = new(maps.SafeSliceMap[string, string])
	)
	macros.Range(func(key string, value string) bool {
		if !m.Has(key) {
			// mylog.Warning(key, value)
			macros.Delete(key)
			// return true
		}
		// mylog.Warning(key, value)
		return true
	})
```

stack trace:
```go
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\Admin\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\Admin\AppData\Local\JetBrains\GoLand2024.3\tmp\GoLand\___TestBindSdk_in_github_com_ddkwork_HyperDbg_sdk_bindgen.test.exe github.com/ddkwork/HyperDbg/sdk/bindgen #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\Admin\AppData\Local\JetBrains\GoLand2024.3\tmp\GoLand\___TestBindSdk_in_github_com_ddkwork_HyperDbg_sdk_bindgen.test.exe -test.v=test2json -test.paniconexit0 -test.run ^\QTestBindSdk\E$ #gosetup
2024-11-30 16:12:49    Trace ->  --------- title --------- │  ------------------ info ------------------ //runtime.doInit1+0xec C:/Program Files/Go/src/runtime/proc.go:7290
2024-11-30 16:12:49    Trace ->             TargetFilePath │  C:\Users\Admin\AppData\Local\hyperdbg\cache\J2PjdXi2KSPVDeg_Je-wilKnxrU11zNn5-usYjB7dPw\hyperkd.sys //github.com/ddkwork/HyperDbg/sdk.init.0+0x254 D:/workspace/workspace/gui/sdk/init.go:29
=== RUN   TestBindSdk
2024-11-30 16:12:49    Trace ->                      merge │  bugfix.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader+0x22c D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:25
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\BasicTypes.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\Connection.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\Constants.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\DataTypes.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\ErrorCodes.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\Events.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\HardwareDebugger.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\Ioctls.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\Pcie.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\RequestStructures.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\ScriptEngineCommonDefinitions.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Headers\Symbols.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Imports\User\HyperDbgLibImports.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Imports\User\HyperDbgScriptImports.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->                      merge │  SDK\Imports\User\HyperDbgSymImports.h //github.com/ddkwork/HyperDbg/sdk/bindgen.TestMergeHeader.func1+0x10f D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:31
2024-11-30 16:12:49    Trace ->           number of macros │  453 //github.com/ddkwork/HyperDbg/sdk/bindgen.TestBindMacros+0x99 D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:50
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc00014c9c0, {0xb93e3f?, 0x7ffcf7860f80?}, 0x22a0a20)
	C:/Program Files/Go/src/testing/testing.go:1751 +0x392
testing.runTests.func1(0xc00014c9c0)
	C:/Program Files/Go/src/testing/testing.go:2168 +0x37
testing.tRunner(0xc00014c9c0, 0xc000047c70)
	C:/Program Files/Go/src/testing/testing.go:1690 +0xcb
testing.runTests(0xc000008258, {0x28d2920, 0x5, 0x5}, {0x473990?, 0x4735fa?, 0x0?})
	C:/Program Files/Go/src/testing/testing.go:2166 +0x43d
testing.(*M).Run(0xc0000c2320)
	C:/Program Files/Go/src/testing/testing.go:2034 +0x64a
main.main()
	_testmain.go:53 +0x9b

goroutine 34 [sync.RWMutex.Lock]:
sync.runtime_SemacquireRWMutex(0x416345?, 0x20?, 0xc000153b80?)
	C:/Program Files/Go/src/runtime/sema.go:105 +0x25
sync.(*RWMutex).Lock(0xc000083dc0?)
	C:/Program Files/Go/src/sync/rwmutex.go:153 +0x6a
github.com/goradd/maps.(*SafeSliceMap[...]).Delete(0x236b3a0, {0xc0001c87a0, 0x6})
	D:/workspace/workspace/vendor/github.com/goradd/maps/safe_slice_map.go:76 +0x3f
github.com/ddkwork/HyperDbg/sdk/bindgen.TestBindMacros.func1({0xc0001c87a0, 0x6}, {0xc0001c87a0?, 0x6?})
	D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:59 +0x5f
github.com/goradd/maps.(*SliceMap[...]).Range(0x236f560, 0xc000083f20)
	D:/workspace/workspace/vendor/github.com/goradd/maps/slice_map.go:334 +0xb0
github.com/goradd/maps.(*SafeSliceMap[...]).Range(0xb98bcb?, 0x3?)
	D:/workspace/workspace/vendor/github.com/goradd/maps/safe_slice_map.go:195 +0xa5
github.com/ddkwork/HyperDbg/sdk/bindgen.TestBindMacros(0x548f33?)
	D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:56 +0xef
github.com/ddkwork/HyperDbg/sdk/bindgen.TestBindSdk(0xc00014cd00)
	D:/workspace/workspace/gui/sdk/bindgen/bind_test.go:184 +0x25
testing.tRunner(0xc00014cd00, 0x22a0a20)
	C:/Program Files/Go/src/testing/testing.go:1690 +0xcb
created by testing.(*T).Run in goroutine 1
	C:/Program Files/Go/src/testing/testing.go:1743 +0x377


Process finished with the exit code 1


```

**Comment by spekary** [comment]
This is a known issue. It was documented for SafeMap, but not SafeSliceMap. See this from SafeMap.Range:

// During this process, the map will be locked, so do not pass a function that will take
// significant amounts of time, nor will call into other methods of the SafeMap which might also need a lock.

**Comment by ddkwork** [comment]
The purpose of range is to add, delete, change and check, if you can not operate within the traversal callback to add, delete, change and check related things, each traversal have to write several lines of code, equivalent to their own realization of the function of the range method is not it?Also, I use slicemap for all my modules because it's in a fixed order, if I understand correctly. Thanks for the library!

**Comment by spekary** [comment]
It's similar to a standard map. You can't iterate a go map with range and change the map while iterating. You will get an undefined response. We could change the Range function to temporarily store a copy of the keys, and then range over this copy. That will prevent the lock conflict, but will use potentially a lot of memory, and still result in an undefined response. I think its better to specifically prevent self changing, and require the caller to duplicate the keys and iterate the keys outside of Range, so its really clear what is happening and memory management is squarely in the hands of the caller. However, I could be persuaded differently.

**Comment by ddkwork** [comment]
mps.stdmap can be do this?

```go
func TestRange(t *testing.T) {
	m := map[string]string{
		"a": "b",
		"c": "d",
	}
	for k := range m {
		println(k)
	}
	for k, v := range m {
		println(k, v)
	}
}

```

**Comment by ddkwork** [comment]
This reminds me of that rang loopvar problem that was fixed in the new version of go, and it occurred to me that I could simulate the way it was written before the fix by applying it to ranges, k:=k v:=v I'll test this later.

**Comment by ddkwork** [comment]
seems you are right, i tested another case:
```go
func TestName(t *testing.T) {
	// maps.CollectSafeSliceMap()
	// maps.CollectSet()
	sliceMap := maps.CollectSliceMap[string, int](func(yield func(string, int) bool) {
		yield("a", 0)
		yield("b", 1)
		yield("c", 2)
		yield("d", 3)
		yield("e", 4)
		yield("f", 5)
		yield("g", 6)
		yield("h", 7)
		yield("i", 8)
		yield("j", 9)
		yield("k", 10)
		yield("l", 11)
		yield("m", 12)
		yield("n", 13)
		yield("o", 14)
		yield("p", 15)
		yield("q", 16)
		yield("r", 17)
		yield("s", 18)
		yield("t", 19)
		yield("u", 20)
		yield("v", 21)
		yield("w", 22)
		yield("x", 23)
		yield("y", 24)
		yield("z", 25)
	})
	sliceMap.Range(func(key string, value int) bool {
		println(strconv.Quote(key), value)
		sliceMap.DeleteFunc(func(s string, i int) bool {
			return sliceMap.Has(key)
		})
		return true
	})
	println(sliceMap.Len())
	// return

	m := map[string]string{
		"a": "b",
		"c": "d",
	}
	for k := range m {
		println(k)
	}
	for k, v := range m {
		println(k, v)
		delete(m, k)
	}
	println(len(m))
}
```

```go
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\Admin\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\Admin\AppData\Local\JetBrains\GoLand2024.3\tmp\GoLand\___TestName_in_github_com_ddkwork_HyperDbg_sdk_bindgen.test.exe github.com/ddkwork/HyperDbg/sdk/bindgen #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\Admin\AppData\Local\JetBrains\GoLand2024.3\tmp\GoLand\___TestName_in_github_com_ddkwork_HyperDbg_sdk_bindgen.test.exe -test.v=test2json -test.paniconexit0 -test.run ^\QTestName\E$ #gosetup
2024-12-01 09:14:17    Trace ->  --------- title --------- │  ------------------ info ------------------ //runtime.doInit1+0xec C:/Program Files/Go/src/runtime/proc.go:7290
2024-12-01 09:14:17    Trace ->             TargetFilePath │  C:\Users\Admin\AppData\Local\hyperdbg\cache\J2PjdXi2KSPVDeg_Je-wilKnxrU11zNn5-usYjB7dPw\hyperkd.sys //github.com/ddkwork/HyperDbg/sdk.init.0+0x254 D:/workspace/workspace/gui/sdk/init.go:29
=== RUN   TestName
"a" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
"" 0
0
a
c
a b
c d
0
--- PASS: TestName (0.00s)
PASS

Process finished with the exit code 0


```
